# Generated by Django 6.0.3 on 2026-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('loan_amnt', models.FloatField(help_text='Loan amount requested')),
                ('annual_inc', models.FloatField(help_text='Annual income')),
                ('installment', models.FloatField(help_text='Monthly installment')),
                ('emp_length', models.FloatField(help_text='Employment length in years')),
                ('home_ownership', models.CharField(choices=[('RENT', 'Rent'), ('OWN', 'Own'), ('MORTGAGE', 'Mortgage'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(choices=[('debt_consolidation', 'Debt Consolidation'), ('credit_card', 'Credit Card'), ('home_improvement', 'Home Improvement'), ('other', 'Other'), ('major_purchase', 'Major Purchase'), ('medical', 'Medical'), ('small_business', 'Small Business'), ('car', 'Car'), ('vacation', 'Vacation'), ('moving', 'Moving'), ('house', 'House'), ('wedding', 'Wedding'), ('educational', 'Educational'), ('renewable_energy', 'Renewable Energy')], max_length=50)),
                ('grade', models.CharField(help_text='Loan grade A-G', max_length=2)),
                ('dti', models.FloatField(help_text='Debt to income ratio')),
                ('delinq_2yrs', models.FloatField(default=0, help_text='Delinquencies in last 2 years')),
                ('open_acc', models.FloatField(help_text='Number of open accounts')),
                ('pub_rec', models.FloatField(default=0, help_text='Public records')),
                ('revol_bal', models.FloatField(help_text='Revolving balance')),
                ('revol_util', models.FloatField(help_text='Revolving utilization rate')),
                ('total_acc', models.FloatField(help_text='Total accounts')),
                ('mort_acc', models.FloatField(default=0, help_text='Mortgage accounts')),
                ('pub_rec_bankruptcies', models.FloatField(default=0, help_text='Bankruptcies')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('VERY_HIGH', 'Very High Risk')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
